modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/TeamChorus/Endit/issues"
[[mods]]
modId="endit"
version="${version}"
displayName="Endit!"
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://modrinth.com/mod/endit"
logoFile="icon.png"
authors="Team Chorus, yeoxuhang"
description='''A simple server-side mod that lets you change the End spawn platform position'''
[[dependencies.endit]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.endit]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
