modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/ChorusTeam/Endit/issues"
[[mods]]
modId="endit"
version="${version}"
displayName="Endit!"
displayURL="https://modrinth.com/mod/endit"
logoFile="icon.png"
authors="Team Chorus, yeoxuhang"
description='''A simple server-side mod that lets you change the End spawn platform position'''
[[dependencies.endit]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.endit]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
